### ISSUE TITLE
[BUG] Cannot import the library in version 3.3.9

### ISSUE THREAD

**Issue by nietzscheson** [filipporomani/whatsapp-python#40]
**Describe the bug**
I worked with the 3.2.5 versions until I received a library message to update to 3.3.9 versions and it is impossible to import the library from whatsapp import WhatsApp

**To Reproduce**
    from whatsapp import WhatsApp

  File ~/projects/rentola/core/.venv/lib/python3.11/site-packages/whatsapp/__init__.py:308
    logging.info(f"Message sent to {
                 ^
SyntaxError: unterminated string literal (detected at line 308)

**Comment by filipporomani** [comment]
This is fixed! Before the new release, you can install the library by using git: 
```bash
git clone https://github.com/filipporomani/whatsapp.git
cd whatsapp
pip install .
```

This should fix your issue. 

Also, I think the problem is related to your python version (as I cannot reproduce the issue with py 3.12 but can with some older versions). 
If you want, you can also try to update python (if you have an old version) and see if the issue persists.

Thank you for reporting the issue!
